### ISSUE TITLE
Can not create a account or sign in

### ISSUE THREAD

**Issue by JeelRajodiya** [RajVarsani/ZestX#2]
I have tried login in with the visitor's credentials 

mail: 404ironman404@gmail.com
pass: 2W5wYY3JZ1LE8V16@

![image](https://github.com/ZestX-IIIT/ZestX-Frontend/assets/63534268/05f9dcca-f9dc-456a-90a2-5321b84dbaac)

**Comment by RajVarsani** [comment]
@JeelRajodiya Thanks for pointing out, It is due to the backend server is not running currently. Not an issue to worrt about. If you are facing issue setting it up locally then let me know, Otherwise we can close this issue.
